apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres

commonLabels:
  app.kubernetes.io/name: postgres

resources:
- namespace.yaml
- deployments/postgres.yaml
- deployments/pgadmin.yaml
- pvc/postgres.yaml
- pvc/pgadmin.yaml
- services/postgres.yaml
- services/pgadmin.yaml
- ingress.yaml
- externalsecrets/pgadmin-config.yaml
- externalsecrets/pg-config.yaml

configMapGenerator:
  - name: pgadmin-config
    envs:
      - configs/pgadmin.env
